spring:
  application:
    name: to-do

  datasource:
    url: jdbc:postgresql://localhost:5432/todo_db
    username: todo_user
    password: a6f41ce@DB
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 5acae913ffc322
    password: e26d35346f3aad
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  logging:
    level:
      org.springframework.mail: DEBUG
